include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    sort_pub_dependencies: false
    avoid_classes_with_only_static_members: false
    use_setters_to_change_properties: false
    avoid_redundant_argument_values: false
