include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    sort_pub_dependencies: false
    avoid_classes_with_only_static_members: false
